### ISSUE TITLE
Python3 failure: compare shape (tuple) with scalar

### ISSUE THREAD

**Issue by marscher** [markovmodel/variational#18]
```
======================================================================
ERROR: test_WrongDimension (variational.estimators.tests.TestEstimator.TestEstimator)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/tests/TestEstimator.py", line 33, in setUp
    self.estimator.add(self.traj0)
  File "/home/marscher/miniconda/envs/_test/lib/python3.4/site-packages/variational-0+untagged.42.g74ce608.dirty-py3.4-linux-x86_64.egg/variational/estimators/lagged_correlation.py", line 44, in add
    if X.shape <= self.tau:
TypeError: unorderable types: tuple() <= int()
```

**Comment by marscher** [comment]
Background information:
http://python3porting.com/problems.html#unorderable-types-cmp-and-cmp

**Comment by marscher** [comment]
is X's shape quadratic?
