### ISSUE TITLE
installing devel_Feliks branch

### ISSUE THREAD

**Issue by euhruska** [markovmodel/variational#34]
I tried installing the branch devel_Feliks, but got the following error:

```
python setup.py install
usage: git rev-list [OPTION] <commit-id>... [ -- paths... ]
  limiting output:
    --max-count=nr
    --max-age=epoch
    --min-age=epoch
    --sparse
    --no-merges
    --remove-empty
    --all
    --branches
    --tags
    --remotes
    --stdin
    --quiet
  ordering output:
    --topo-order
    --date-order
    --reverse
  formatting output:
    --parents
    --children
    --objects | --objects-edge
    --unpacked
    --header | --pretty
    --abbrev=nr | --no-abbrev
    --abbrev-commit
    --left-right
  special purpose:
    --bisect
    --bisect-vars
    --bisect-all
Traceback (most recent call last):
  File "setup.py", line 165, in <module>
    version=versioneer.get_version(),
  File "/dascratch/eh22/variational/versioneer.py", line 1405, in get_version
    return get_versions()["version"]
  File "/dascratch/eh22/variational/versioneer.py", line 1380, in get_versions
    pieces = from_vcs_f(cfg.tag_prefix, root, verbose)
  File "/dascratch/eh22/variational/versioneer.py", line 1076, in git_pieces_from_vcs
    pieces["distance"] = int(count_out)  # total number of commits
TypeError: int() argument must be a string or a number, not 'NoneType'
```

Is the problem on my side or in variational/versioneer.py?

**Comment by marscher** [comment]
It seems related to the git client on your system. What do you have? (git --version)

It guess this is an upstream issue of versioneer then. Maybe try installing a recent git with conda.

**Comment by euhruska** [comment]
Thanks, fixed
